on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.13.15'
      - shell: bash
        run: mkdir -p "$HOME/.config/astra"
      - shell: bash
        env:
          SA: ${{ secrets.ASTRA_SERVICE_ACCOUNT }}
        run: |
          echo "$SA" > "$HOME/.config/astra/sa.json"
      - shell: bash
        env:
          ASTRA_TOKEN: ${{ secrets.ASTRA_TOKEN }}
        run: |
          echo "$ASTRA_TOKEN" > "$HOME/.config/astra/token"
      - name: ci
        run: ./script/cibuild
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
        
    
